In [121]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [122]:
#read data
data=pd.read_csv("roo_data.csv")
data.head(5)


Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                        69                        63   
1                                        78                        62   
2                                        71                        86   
3                                        76                        87   
4                                        92                        62   

   Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                  78                                  87   
1                                  73                                  60   
2                                  91                                  87   
3                                  60                                  84   
4                                  90                                  67   

   Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                               94                                  94   
1                               71                                  70   
2                               61                                  81   
3                               89                                  73   
4                               71                                  89   

   Percentage in Computer Architecture  Percentage in Mathematics  \
0                                   87                         84   
1                                   73                         84   
2                                   72                         72   
3                                   62                         88   
4                                   73                         71   

   Percentage in Communication skills  Hours working per day  ...  \
0                                  61                      9  ...   
1                                  91                     12  ...   
2                                  94                     11  ...   
3                                  69                      7  ...   
4                                  73                      4  ...   

   Interested Type of Books  Salary Range Expected  In a Realtionship?  \
0              Prayer books                 salary                  no   
1                 Childrens                 salary                 yes   
2                    Travel                   Work                  no   
3                   Romance                   Work                 yes   
4                 Cookbooks                 salary                  no   

   Gentle or Tuff behaviour? Management or Technical Salary/work  \
0                   stubborn              Management      salary   
1                     gentle               Technical      salary   
2                   stubborn              Management        work   
3                     gentle              Management        work   
4                   stubborn              Management        work   

  hard/smart worker worked in teams ever? Introvert  \
0       hard worker                   yes        no   
1       hard worker                    no       yes   
2       hard worker                    no       yes   
3      smart worker                   yes       yes   
4       hard worker                   yes       yes   

               Suggested Job Role  
0              Database Developer  
1            Portal Administrator  
2            Portal Administrator  
3  Systems Security Administrator  
4        Business Systems Analyst  

[5 rows x 39 columns]

In [123]:
print("The dimensions of the data is " + str(data.shape))

The dimensions of the data is (20000, 39)


In [124]:
data.info() #check for any missing fields 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 39 columns):
 #   Column                                    Non-Null Count  Dtype 
---  ------                                    --------------  ----- 
 0   Acedamic percentage in Operating Systems  20000 non-null  int64 
 1   percentage in Algorithms                  20000 non-null  int64 
 2   Percentage in Programming Concepts        20000 non-null  int64 
 3   Percentage in Software Engineering        20000 non-null  int64 
 4   Percentage in Computer Networks           20000 non-null  int64 
 5   Percentage in Electronics Subjects        20000 non-null  int64 
 6   Percentage in Computer Architecture       20000 non-null  int64 
 7   Percentage in Mathematics                 20000 non-null  int64 
 8   Percentage in Communication skills        20000 non-null  int64 
 9   Hours working per day                     20000 non-null  int64 
 10  Logical quotient rating                   2000

In [125]:
#remove unnecessary data
data.drop(['Extra-courses did', 'reading and writing skills','Taken inputs from seniors or elders','interested in games','Interested Type of Books','Salary Range Expected','In a Realtionship?','Gentle or Tuff behaviour?','Salary/work','Introvert','hackathons','Job/Higher Studies?','hard/smart worker', 'Hours working per day','talenttests taken?', 'olympiads','can work long time before system?'], axis=1, inplace=True)
data.shape #we have 22 columns now

(20000, 22)

In [126]:
#replace 'yes'/'no' with 1/0
data["self-learning capability?"].replace(to_replace=['no', 'yes'], value=[0, 1], inplace=True)
data['self-learning capability?'].head()

0    1
1    0
2    0
3    1
4    0
Name: self-learning capability?, dtype: int64

In [128]:
#binary encoding 
technical=pd.get_dummies(data['Management or Technical'], drop_first=True)
technical.head()

Technical
0          0
1          1
2          0
3          0
4          0

In [129]:
#adding this field to main dataframe
data=pd.concat([data, technical], axis=1)
data.drop(['Management or Technical'], axis=1, inplace=True)
data.head()

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                        69                        63   
1                                        78                        62   
2                                        71                        86   
3                                        76                        87   
4                                        92                        62   

   Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                  78                                  87   
1                                  73                                  60   
2                                  91                                  87   
3                                  60                                  84   
4                                  90                                  67   

   Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                               94                                  94   
1                               71                                  70   
2                               61                                  81   
3                               89                                  73   
4                               71                                  89   

   Percentage in Computer Architecture  Percentage in Mathematics  \
0                                   87                         84   
1                                   73                         84   
2                                   72                         72   
3                                   62                         88   
4                                   73                         71   

   Percentage in Communication skills  Logical quotient rating  ...  \
0                                  61                        4  ...   
1                                  91                        7  ...   
2                                  94                        1  ...   
3                                  69                        1  ...   
4                                  73                        5  ...   

   self-learning capability?     certifications          workshops  \
0                          1  shell programming    cloud computing   
1                          0   machine learning  database security   
2                          0    app development   web technologies   
3                          1             python       data science   
4                          0    app development    cloud computing   

  memory capability score    Interested subjects   interested career area   \
0               excellent        cloud computing          system developer   
1                  medium               networks  Business process analyst   
2               excellent                hacking                 developer   
3               excellent               networks                   testing   
4               excellent  Computer Architecture                   testing   

  Type of company want to settle in? worked in teams ever?  \
0                       Web Services                   yes   
1                      SAaS services                    no   
2                Sales and Marketing                    no   
3  Testing and Maintainance Services                   yes   
4                product development                   yes   

               Suggested Job Role Technical  
0              Database Developer         0  
1            Portal Administrator         1  
2            Portal Administrator         0  
3  Systems Security Administrator         0  
4        Business Systems Analyst         0  

[5 rows x 22 columns]

In [130]:
#binary encoding
subjects=pd.get_dummies(data['Interested subjects'], drop_first=True)
subjects.head()

IOT  Management  Software Engineering  cloud computing  data engineering  \
0    0           0                     0                1                 0   
1    0           0                     0                0                 0   
2    0           0                     0                0                 0   
3    0           0                     0                0                 0   
4    0           0                     0                0                 0   

   hacking  networks  parallel computing  programming  
0        0         0                   0            0  
1        0         1                   0            0  
2        1         0                   0            0  
3        0         1                   0            0  
4        0         0                   0            0

In [131]:
#binary encoding
career=pd.get_dummies(data['interested career area '], drop_first=True)
career.head()

cloud computing  developer  security  system developer  testing
0                0          0         0                 1        0
1                0          0         0                 0        0
2                0          1         0                 0        0
3                0          0         0                 0        1
4                0          0         0                 0        1

In [132]:
#binary encoding 
company=pd.get_dummies(data['Type of company want to settle in?'], drop_first=True)
company.head()

Cloud Services  Finance  Product based  SAaS services  Sales and Marketing  \
0               0        0              0              0                    0   
1               0        0              0              1                    0   
2               0        0              0              0                    1   
3               0        0              0              0                    0   
4               0        0              0              0                    0   

   Service Based  Testing and Maintainance Services  Web Services  \
0              0                                  0             1   
1              0                                  0             0   
2              0                                  0             0   
3              0                                  1             0   
4              0                                  0             0   

   product development  
0                    0  
1                    0  
2                    0  
3                    0  
4                    1

In [133]:
#binary encoding
certificates=pd.get_dummies(data['certifications'], drop_first=True)
certificates.head()

distro making  full stack  hadoop  information security  machine learning  \
0              0           0       0                     0                 0   
1              0           0       0                     0                 1   
2              0           0       0                     0                 0   
3              0           0       0                     0                 0   
4              0           0       0                     0                 0   

   python  r programming  shell programming  
0       0              0                  1  
1       0              0                  0  
2       0              0                  0  
3       1              0                  0  
4       0              0                  0

In [134]:
#adding these fields to dataframe
data=pd.concat([data, subjects, career, certificates], axis=1)
data.drop(['Type of company want to settle in?', 'interested career area ','Interested subjects','certifications'], axis=1, inplace=True)
data.head()

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                        69                        63   
1                                        78                        62   
2                                        71                        86   
3                                        76                        87   
4                                        92                        62   

   Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                  78                                  87   
1                                  73                                  60   
2                                  91                                  87   
3                                  60                                  84   
4                                  90                                  67   

   Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                               94                                  94   
1                               71                                  70   
2                               61                                  81   
3                               89                                  73   
4                               71                                  89   

   Percentage in Computer Architecture  Percentage in Mathematics  \
0                                   87                         84   
1                                   73                         84   
2                                   72                         72   
3                                   62                         88   
4                                   73                         71   

   Percentage in Communication skills  Logical quotient rating  ...  \
0                                  61                        4  ...   
1                                  91                        7  ...   
2                                  94                        1  ...   
3                                  69                        1  ...   
4                                  73                        5  ...   

   system developer  testing  distro making full stack hadoop  \
0                 1        0              0          0      0   
1                 0        0              0          0      0   
2                 0        0              0          0      0   
3                 0        1              0          0      0   
4                 0        1              0          0      0   

  information security machine learning  python  r programming  \
0                    0                0       0              0   
1                    0                1       0              0   
2                    0                0       0              0   
3                    0                0       1              0   
4                    0                0       0              0   

   shell programming  
0                  1  
1                  0  
2                  0  
3                  0  
4                  0  

[5 rows x 40 columns]

In [135]:
#new mean of grades field
df=data.iloc[:,:8]
df['Computer Science Percentage'] = df.mean(axis=1)
df

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                            69                        63   
1                                            78                        62   
2                                            71                        86   
3                                            76                        87   
4                                            92                        62   
...                                         ...                       ...   
19995                                        83                        67   
19996                                        80                        69   
19997                                        83                        70   
19998                                        68                        87   
19999                                        73                        77   

       Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                      78                                  87   
1                                      73                                  60   
2                                      91                                  87   
3                                      60                                  84   
4                                      90                                  67   
...                                   ...                                 ...   
19995                                  62                                  63   
19996                                  83                                  87   
19997                                  80                                  87   
19998                                  91                                  88   
19999                                  74                                  84   

       Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                                   94                                  94   
1                                   71                                  70   
2                                   61                                  81   
3                                   89                                  73   
4                                   71                                  89   
...                                ...                                 ...   
19995                               81                                  74   
19996                               82                                  66   
19997                               64                                  85   
19998                               66                                  74   
19999                               70                                  65   

       Percentage in Computer Architecture  Percentage in Mathematics  \
0                                       87                         84   
1                                       73                         84   
2                                       72                         72   
3                                       62                         88   
4                                       73                         71   
...                                    ...                        ...   
19995                                   90                         84   
19996                                   66                         92   
19997                                   69                         94   
19998                                   61                         87   
19999                                   92                         73   

       Computer Science Percentage  
0                           82.000  
1                           71.375  
2                           77.625  
3                           77.375  
4                           76.875  
...                            ...  
19995                       75.500  

In [136]:
#add the mean grade field to the dataframe
data.drop(['Acedamic percentage in Operating Systems',	'percentage in Algorithms'	,'Percentage in Programming Concepts','Percentage in Software Engineering',	'Percentage in Computer Networks',	'Percentage in Electronics Subjects'	,'Percentage in Computer Architecture',	'Percentage in Mathematics'],axis=1, inplace=True)
data=pd.concat([data,df['Computer Science Percentage']], axis=1)
#removing attributes based on hit and trial on accuracy
data.drop(['workshops','worked in teams ever?','memory capability score','public speaking points'], inplace=True, axis=1)

In [137]:
#unique values of Jog Roles
no_of_categories=data['Suggested Job Role'].unique()
no_of_categories


array(['Database Developer', 'Portal Administrator',
       'Systems Security Administrator', 'Business Systems Analyst',
       'Software Systems Engineer', 'Business Intelligence Analyst',
       'CRM Technical Developer', 'Mobile Applications Developer',
       'UX Designer', 'Quality Assurance Associate', 'Web Developer',
       'Information Security Analyst', 'CRM Business Analyst',
       'Technical Support', 'Project Manager',
       'Information Technology Manager', 'Programmer Analyst',
       'Design & UX', 'Solutions Architect', 'Systems Analyst',
       'Network Security Administrator', 'Data Architect',
       'Software Developer', 'E-Commerce Analyst',
       'Technical Services/Help Desk/Tech Support',
       'Information Technology Auditor', 'Database Manager',
       'Applications Developer', 'Database Administrator',
       'Network Engineer', 'Software Engineer', 'Technical Engineer',
       'Network Security Engineer',
       'Software Quality Assurance (QA) / Testi

In [138]:
#merging job roles in broad categories 
data['Suggested Job Role'].replace(to_replace=['Database Developer', 'Portal Administrator',
       'Systems Security Administrator', 'Business Systems Analyst',
       'Software Systems Engineer', 'Business Intelligence Analyst',
       'CRM Technical Developer', 'Mobile Applications Developer',
       'UX Designer', 'Quality Assurance Associate', 'Web Developer',
       'Information Security Analyst', 'CRM Business Analyst',
       'Technical Support', 'Project Manager',
       'Information Technology Manager', 'Programmer Analyst',
       'Design & UX', 'Solutions Architect', 'Systems Analyst',
       'Network Security Administrator', 'Data Architect',
       'Software Developer', 'E-Commerce Analyst',
       'Technical Services/Help Desk/Tech Support',
       'Information Technology Auditor', 'Database Manager',
       'Applications Developer', 'Database Administrator',
       'Network Engineer', 'Software Engineer', 'Technical Engineer',
       'Network Security Engineer',
       'Software Quality Assurance (QA) / Testing'], 
       value=['Data Analyst', 'Technical Analyst','Security/Networking Analyst','Business Analyst','Software/UX Analyst','Business Analyst',
             'Technical Analyst','Software/UX Analyst',
             'Software/UX Analyst', 'Technical Analyst','Software/UX Analyst',
             'Security/Networking Analyst','Business Analyst','Technical Analyst','Business Analyst',
             'Security/Networking Analyst', 'Software/UX Analyst',
             'Software/UX Analyst', 'Technical Analyst', 'Technical Analyst','Security/Networking Analyst', 'Data Analyst', 
             'Software/UX Analyst', 'Business Analyst', 'Technical Analyst','Security/Networking Analyst','Data Analyst','Software/UX Analyst',
             'Data Analyst', 'Security/Networking Analyst', 'Software/UX Analyst','Technical Analyst','Security/Networking Analyst','Technical Analyst'], inplace=True)

In [139]:


#New categories of Job roles
data['Suggested Job Role'].unique()

array(['Data Analyst', 'Technical Analyst', 'Security/Networking Analyst',
       'Business Analyst', 'Software/UX Analyst'], dtype=object)

In [140]:

data.head()


Percentage in Communication skills  Logical quotient rating  \
0                                  61                        4   
1                                  91                        7   
2                                  94                        1   
3                                  69                        1   
4                                  73                        5   

   coding skills rating  self-learning capability?  \
0                     4                          1   
1                     2                          0   
2                     1                          0   
3                     2                          1   
4                     6                          0   

            Suggested Job Role  Technical  IOT  Management  \
0                 Data Analyst          0    0           0   
1            Technical Analyst          1    0           0   
2            Technical Analyst          0    0           0   
3  Security/Networking Analyst          0    0           0   
4             Business Analyst          0    0           0   

   Software Engineering  cloud computing  ...  testing  distro making  \
0                     0                1  ...        0              0   
1                     0                0  ...        0              0   
2                     0                0  ...        0              0   
3                     0                0  ...        1              0   
4                     0                0  ...        1              0   

   full stack  hadoop  information security  machine learning  python  \
0           0       0                     0                 0       0   
1           0       0                     0                 1       0   
2           0       0                     0                 0       0   
3           0       0                     0                 0       1   
4           0       0                     0                 0       0   

   r programming  shell programming  Computer Science Percentage  
0              0                  1                       82.000  
1              0                  0                       71.375  
2              0                  0                       77.625  
3              0                  0                       77.375  
4              0                  0                       76.875  

[5 rows x 29 columns]

In [141]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.manifold import TSNE
from sklearn.model_selection import KFold

X=data.drop("Suggested Job Role", axis=1)
y=data["Suggested Job Role"]

#split training and testing data
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.1, random_state=1)

#Scaling data 
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)


print("Normalized data: ")
X_train

Normalized data: 


array([[-7.93970481e-01, -3.86869002e-01,  1.55480088e+00, ...,
        -3.57963172e-01, -3.55885901e-01, -2.31011538e+00],
       [ 1.18317073e+00,  9.04805551e-04,  1.55480088e+00, ...,
         2.79358347e+00, -3.55885901e-01,  2.02039473e-01],
       [ 1.28202779e+00, -7.74642809e-01, -1.55111260e+00, ...,
        -3.57963172e-01, -3.55885901e-01,  5.50949870e-01],
       ...,
       [ 1.38088485e+00,  1.16422623e+00,  7.78322506e-01, ...,
        -3.57963172e-01, -3.55885901e-01, -1.54251251e+00],
       [-1.48596990e+00, -1.55019042e+00, -7.74634234e-01, ...,
        -3.57963172e-01, -3.55885901e-01, -1.50762147e+00],
       [-5.96256360e-01,  1.16422623e+00, -1.55111260e+00, ...,
        -3.57963172e-01, -3.55885901e-01,  3.06712592e-01]])

In [142]:

#ANN model 
from sklearn.neural_network import MLPClassifier
MLP=MLPClassifier(hidden_layer_sizes=(40,20,2), max_iter=1000,activation = 'relu',solver='adam',random_state=1)
MLP.fit(X_train, y_train.values.ravel())


MLPClassifier(hidden_layer_sizes=(40, 20, 2), max_iter=1000, random_state=1)

In [143]:
predictions=MLP.predict(X_test)
predictions


array(['Software/UX Analyst', 'Software/UX Analyst',
       'Software/UX Analyst', ..., 'Software/UX Analyst',
       'Software/UX Analyst', 'Software/UX Analyst'], dtype='<U27')

In [144]:
#classwise accuracy
print("Classification report: ")
print(classification_report(y_test, predictions))

Classification report: 


c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                             precision    recall  f1-score   support

           Business Analyst       0.00      0.00      0.00      1156
               Data Analyst       0.11      0.02      0.04       906
Security/Networking Analyst       0.00      0.00      0.00      1862
        Software/UX Analyst       0.25      0.86      0.39      2022
          Technical Analyst       0.24      0.11      0.15      2054

                   accuracy                           0.25      8000
                  macro avg       0.12      0.20      0.12      8000
               weighted avg       0.14      0.25      0.14      8000



c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [145]:
print("Confusion matrix: ")
print(confusion_matrix(y_test, predictions))
from sklearn.metrics import accuracy_score
acc = accuracy_score(predictions , y_test)
print("The accuracy of model is", acc*100,"%")

Confusion matrix: 
[[   0   32    0  983  141]
 [   0   22    0  787   97]
 [   0   50    0 1599  213]
 [   0   50    0 1738  234]
 [   0   44    0 1788  222]]
The accuracy of model is 24.775 %


In [146]:
#Assignment 1 logic
dataset=pd.read_csv("roo_data.csv")
df1=dataset.iloc[:,0:9]  #grades
df2=dataset.iloc[:,17:19] #electives
df3=dataset.iloc[:,23:25] #interests
df4=dataset.iloc[:,-1]    #Suggested Job Roles
new_df=pd.concat([df1,df2,df3,df4], axis=1)
new_df.head() #new data to work with

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                        69                        63   
1                                        78                        62   
2                                        71                        86   
3                                        76                        87   
4                                        92                        62   

   Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                  78                                  87   
1                                  73                                  60   
2                                  91                                  87   
3                                  60                                  84   
4                                  90                                  67   

   Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                               94                                  94   
1                               71                                  70   
2                               61                                  81   
3                               89                                  73   
4                               71                                  89   

   Percentage in Computer Architecture  Percentage in Mathematics  \
0                                   87                         84   
1                                   73                         84   
2                                   72                         72   
3                                   62                         88   
4                                   73                         71   

   Percentage in Communication skills     certifications          workshops  \
0                                  61  shell programming    cloud computing   
1                                  91   machine learning  database security   
2                                  94    app development   web technologies   
3                                  69             python       data science   
4                                  73    app development    cloud computing   

     Interested subjects   interested career area   \
0        cloud computing          system developer   
1               networks  Business process analyst   
2                hacking                 developer   
3               networks                   testing   
4  Computer Architecture                   testing   

               Suggested Job Role  
0              Database Developer  
1            Portal Administrator  
2            Portal Administrator  
3  Systems Security Administrator  
4        Business Systems Analyst

In [147]:
#renaming columns based on attributes required(for eg. electives, grades and interests)
new_df.rename(columns = {'certifications':'Elective1','workshops':'Elective2'}, inplace = True)
new_df.head()

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                        69                        63   
1                                        78                        62   
2                                        71                        86   
3                                        76                        87   
4                                        92                        62   

   Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                  78                                  87   
1                                  73                                  60   
2                                  91                                  87   
3                                  60                                  84   
4                                  90                                  67   

   Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                               94                                  94   
1                               71                                  70   
2                               61                                  81   
3                               89                                  73   
4                               71                                  89   

   Percentage in Computer Architecture  Percentage in Mathematics  \
0                                   87                         84   
1                                   73                         84   
2                                   72                         72   
3                                   62                         88   
4                                   73                         71   

   Percentage in Communication skills          Elective1          Elective2  \
0                                  61  shell programming    cloud computing   
1                                  91   machine learning  database security   
2                                  94    app development   web technologies   
3                                  69             python       data science   
4                                  73    app development    cloud computing   

     Interested subjects   interested career area   \
0        cloud computing          system developer   
1               networks  Business process analyst   
2                hacking                 developer   
3               networks                   testing   
4  Computer Architecture                   testing   

               Suggested Job Role  
0              Database Developer  
1            Portal Administrator  
2            Portal Administrator  
3  Systems Security Administrator  
4        Business Systems Analyst

In [148]:
#binary encoding
ele1=pd.get_dummies(new_df['Elective1'], drop_first=True)
ele1.head()

distro making  full stack  hadoop  information security  machine learning  \
0              0           0       0                     0                 0   
1              0           0       0                     0                 1   
2              0           0       0                     0                 0   
3              0           0       0                     0                 0   
4              0           0       0                     0                 0   

   python  r programming  shell programming  
0       0              0                  1  
1       0              0                  0  
2       0              0                  0  
3       1              0                  0  
4       0              0                  0

In [149]:
#binary encoding
ele2=pd.get_dummies(new_df['Elective2'], drop_first=True)
ele2.head()

data science  database security  game development  hacking  \
0             0                  0                 0        0   
1             0                  1                 0        0   
2             0                  0                 0        0   
3             1                  0                 0        0   
4             0                  0                 0        0   

   system designing  testing  web technologies  
0                 0        0                 0  
1                 0        0                 0  
2                 0        0                 1  
3                 0        0                 0  
4                 0        0                 0

In [150]:
#binary encoding 
area=pd.get_dummies(new_df['interested career area '], drop_first=True)
area.head()

cloud computing  developer  security  system developer  testing
0                0          0         0                 1        0
1                0          0         0                 0        0
2                0          1         0                 0        0
3                0          0         0                 0        1
4                0          0         0                 0        1

In [151]:
#binary encoding
subs=pd.get_dummies(new_df['Interested subjects'], drop_first=True)
subs.head()

IOT  Management  Software Engineering  cloud computing  data engineering  \
0    0           0                     0                1                 0   
1    0           0                     0                0                 0   
2    0           0                     0                0                 0   
3    0           0                     0                0                 0   
4    0           0                     0                0                 0   

   hacking  networks  parallel computing  programming  
0        0         0                   0            0  
1        0         1                   0            0  
2        1         0                   0            0  
3        0         1                   0            0  
4        0         0                   0            0

In [152]:
#add new fields to the original dataframe
new_df=pd.concat([new_df, ele1, ele2, subs, area], axis=1)
new_df.drop(['interested career area ', 'Interested subjects','Elective1','Elective2'], inplace=True, axis=1)
new_df.head()

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                            69                        63   
1                                            78                        62   
2                                            71                        86   
3                                            76                        87   
4                                            92                        62   
...                                         ...                       ...   
19995                                        83                        67   
19996                                        80                        69   
19997                                        83                        70   
19998                                        68                        87   
19999                                        73                        77   

       Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                      78                                  87   
1                                      73                                  60   
2                                      91                                  87   
3                                      60                                  84   
4                                      90                                  67   
...                                   ...                                 ...   
19995                                  62                                  63   
19996                                  83                                  87   
19997                                  80                                  87   
19998                                  91                                  88   
19999                                  74                                  84   

       Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                                   94                                  94   
1                                   71                                  70   
2                                   61                                  81   
3                                   89                                  73   
4                                   71                                  89   
...                                ...                                 ...   
19995                               81                                  74   
19996                               82                                  66   
19997                               64                                  85   
19998                               66                                  74   
19999                               70                                  65   

       Percentage in Computer Architecture  Percentage in Mathematics  \
0                                       87                         84   
1                                       73                         84   
2                                       72                         72   
3                                       62                         88   
4                                       73                         71   
...                                    ...                        ...   
19995                                   90                         84   
19996                                   66                         92   
19997                                   69                         94   
19998                                   61                         87   
19999                                   92                         73   

       Percentage in Communication skills  \
0                                      61   
1                                      91   
2                                      94   
3                                      69   
4                                      73   
...                      

In [153]:
#merging job roles in broad categories 
new_df['Suggested Job Role'].replace(to_replace=['Database Developer', 'Portal Administrator',
       'Systems Security Administrator', 'Business Systems Analyst',
       'Software Systems Engineer', 'Business Intelligence Analyst',
       'CRM Technical Developer', 'Mobile Applications Developer',
       'UX Designer', 'Quality Assurance Associate', 'Web Developer',
       'Information Security Analyst', 'CRM Business Analyst',
       'Technical Support', 'Project Manager',
       'Information Technology Manager', 'Programmer Analyst',
       'Design & UX', 'Solutions Architect', 'Systems Analyst',
       'Network Security Administrator', 'Data Architect',
       'Software Developer', 'E-Commerce Analyst',
       'Technical Services/Help Desk/Tech Support',
       'Information Technology Auditor', 'Database Manager',
       'Applications Developer', 'Database Administrator',
       'Network Engineer', 'Software Engineer', 'Technical Engineer',
       'Network Security Engineer',
       'Software Quality Assurance (QA) / Testing'], 
       value=['Data Analyst', 'Technical Analyst','Security/Networking Analyst','Business Analyst','Software/UX Analyst','Business Analyst',
             'Technical Analyst','Software/UX Analyst',
             'Software/UX Analyst', 'Technical Analyst','Software/UX Analyst',
             'Security/Networking Analyst','Business Analyst','Technical Analyst','Business Analyst',
             'Security/Networking Analyst', 'Software/UX Analyst',
             'Software/UX Analyst', 'Technical Analyst', 'Technical Analyst','Security/Networking Analyst', 'Data Analyst', 
             'Software/UX Analyst', 'Business Analyst', 'Technical Analyst','Security/Networking Analyst','Data Analyst','Software/UX Analyst',
             'Data Analyst', 'Security/Networking Analyst', 'Software/UX Analyst','Technical Analyst','Security/Networking Analyst','Technical Analyst'], inplace=True)

In [159]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.manifold import TSNE
from sklearn.model_selection import KFold

X=new_df.drop("Suggested Job Role", axis=1)
y=new_df["Suggested Job Role"]

#split data in training and testing datasets 
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.25, random_state=1)

#Scaling data 
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)


print("Normalized data: ")
X_train


Normalized data: 


array([[-0.00504299,  1.68562786,  0.49198006, ..., -0.44658735,
        -0.44962639, -0.44757132],
       [-0.10414097,  0.30052816, -0.88961678, ..., -0.44658735,
        -0.44962639, -0.44757132],
       [ 1.58052471, -0.1941503 ,  0.9854075 , ..., -0.44658735,
        -0.44962639, -0.44757132],
       ...,
       [-0.10414097, -1.08457154,  0.0972381 , ..., -0.44658735,
        -0.44962639, -0.44757132],
       [-0.40143491, -1.57925001,  0.39329457, ..., -0.44658735,
        -0.44962639, -0.44757132],
       [-0.00504299, -1.38137862,  0.29460908, ..., -0.44658735,
         2.22406872, -0.44757132]])

In [160]:
#ANN model
from sklearn.neural_network import MLPClassifier
MLP=MLPClassifier(hidden_layer_sizes=(40,20,2), max_iter=1000,activation = 'relu',solver='adam',random_state=1)
MLP.fit(X_train, y_train.values.ravel())

MLPClassifier(hidden_layer_sizes=(40, 20, 2), max_iter=1000, random_state=1)

In [161]:
predictions=MLP.predict(X_test)
predictions


array(['Security/Networking Analyst', 'Security/Networking Analyst',
       'Technical Analyst', ..., 'Security/Networking Analyst',
       'Security/Networking Analyst', 'Security/Networking Analyst'],
      dtype='<U27')

In [162]:
print("Classification Report: ")
print(classification_report(y_test,predictions))

Classification Report: 


c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                             precision    recall  f1-score   support

           Business Analyst       0.00      0.00      0.00       301
               Data Analyst       0.00      0.00      0.00       209
Security/Networking Analyst       0.23      0.53      0.32       467
        Software/UX Analyst       0.26      0.26      0.26       534
          Technical Analyst       0.23      0.17      0.20       489

                   accuracy                           0.24      2000
                  macro avg       0.14      0.19      0.16      2000
               weighted avg       0.18      0.24      0.19      2000



c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [163]:
print("Confusion matrix: ")
print(confusion_matrix(y_test, predictions))
from sklearn.metrics import accuracy_score
acc = accuracy_score(predictions , y_test)
print("The accuracy of model is", acc*100,"%")

Confusion matrix: 
[[  0   0 176  80  45]
 [  0   0 110  58  41]
 [  0   0 248 127  92]
 [  0   0 290 141 103]
 [  0   0 265 139  85]]
The accuracy of model is 23.7 %
